{"metadata":{"role":"symbol","modules":[{"name":"SoulverCore"}],"symbolKind":"case","externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","title":"EvaluationResult.failed","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}]},"abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"title":"Nil answer cases","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A null result"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"title":"EvaluationResult.none","role":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/none"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"title":"EvaluationResult.failed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","url":"\/documentation\/soulvercore\/evaluationresult\/failed","type":"topic","abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}]},"doc://app.soulver.core/documentation/SoulverCore":{"url":"\/documentation\/soulvercore","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","title":"SoulverCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A powerful natural language calculation engine"}],"role":"collection"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","url":"\/documentation\/soulvercore\/evaluationresult\/pending","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}],"type":"topic","abstract":[{"text":"A result that must be fetched asyncronously (probably over a network)","type":"text"}],"role":"symbol","title":"EvaluationResult.pending","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","navigatorTitle":[{"text":"EvaluationResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EvaluationResult","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/soulvercore\/evaluationresult","title":"EvaluationResult","kind":"symbol","abstract":[{"text":"Represents the underlying data of a result of a SoulverCore calculation","type":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"title":"EvaluationResult.error(_:)","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","kind":"typeIdentifier","text":"EvaluationError"},{"text":")","kind":"text"}],"type":"topic"}}}