{"seeAlsoSections":[{"title":"Nil answer cases","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"generated":true}],"abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"metadata":{"externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","title":"EvaluationResult.failed","symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"SoulverCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}]},"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"sections":[],"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/pending","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","type":"topic","role":"symbol","title":"EvaluationResult.pending"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","type":"topic","role":"symbol","title":"EvaluationResult.failed"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"abstract":[{"text":"Represents the underlying data of a result of a SoulverCore calculation","type":"text"}],"title":"EvaluationResult","navigatorTitle":[{"kind":"identifier","text":"EvaluationResult"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","url":"\/documentation\/soulvercore\/evaluationresult","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EvaluationResult","kind":"identifier"}]},"doc://app.soulver.core/documentation/SoulverCore":{"title":"SoulverCore","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","abstract":[{"type":"text","text":"A powerful natural language calculation engine"}],"url":"\/documentation\/soulvercore","kind":"symbol","role":"collection"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/none","abstract":[{"type":"text","text":"A null result"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","type":"topic","role":"symbol","title":"EvaluationResult.none"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EvaluationError","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO"},{"text":")","kind":"text"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","type":"topic","role":"symbol","title":"EvaluationResult.error(_:)"}}}